<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>National Mailing & Marketing</title>	
	<meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="css/responsive-nav.css" type="text/css" />
    <link rel="stylesheet" href="css/style.css"  type="text/css"/>  
    <link rel="stylesheet" href="css/flexslider.css" type="text/css" />
	<script src="js/jquery-1.11.1.min.js"></script>
    <!--load flexslider-->
    <script src="js/jquery.flexslider.js"></script>
    <!--load mobile menu-->
    <script src="js/responsive-nav.js"></script>

	<script type = "text/javascript" >
	    $(function () {
	        var path = location.pathname.split("?");
	        switch (path[0]) {
	            //case "/nmm/home.html":            
	            case "/C:/Users/sophie.jiang/Documents/Work%Item/NMM%Official%Web%May%2015/home.htm":
	                $("#home").addClass("selected");
	                break;
	            //case "/nmm/services.html":              
	            case "/C:/Users/sophie.jiang/Documents/Work%Item/NMM%Official%Web%May%2015/services.htm":
	                $("#services").addClass("selected");
	                break;
	            //case "/nmm/aboutus.html":              
	            case "/C:/Users/sophie.jiang/Documents/Work%Item/NMM%Official%Web%May%2015/aboutus.htm":
	                $("#aboutus").addClass("selected");
	                break;
	            //case "/nmm/contactus.html":              
	            case "/C:/Users/sophie.jiang/Documents/Work%Item/NMM%Official%Web%May%2015/contactus.htm":
	                $("#contactus").addClass("selected");
	                break;
	            //case "/nmm/login.html":              
	            case "/C:/Users/sophie.jiang/Documents/Work%Item/NMM%Official%Web%May%2015/login.htm":
	                $("#login").addClass("selected");
	                break;
	            default:
	                $("#home").addClass("selected");
	        }
	        if ($(window).width() >= 960) {
	            fnHeader();	            
	        } 
            else {
	            fnMobileHeader();
	        }
	        $("#footer").load("footer.htm");

	        $(window).resize(function () {
	            if ($(window).width() >= 960) {
	                fnHeader();
	            }
	            else {
	                fnMobileHeader();
	            }
	        });

	        function fnHeader() {
	            $(".flexslider").flexslider({
	                namespace: "flex-",             //{NEW} String: Prefix string attached to the class of every element generated by the plugin
	                selector: ".slides > li",       //{NEW} Selector: Must match a simple pattern. '{container} > {slide}' -- Ignore pattern at your own peril
	                animation: "fade",              //String: Select your animation type, "fade" or "slide"
	                easing: "swing",               //{NEW} String: Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!
	                direction: "horizontal",        //String: Select the sliding direction, "horizontal" or "vertical"
	                reverse: false,                 //{NEW} Boolean: Reverse the animation direction
	                animationLoop: true,             //Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
	                smoothHeight: false,            //{NEW} Boolean: Allow height of the slider to animate smoothly in horizontal mode  
	                startAt: 0,                     //Integer: The slide that the slider should start on. Array notation (0 = first slide)
	                slideshow: true,                //Boolean: Animate slider automatically
	                slideshowSpeed: 7000,           //Integer: Set the speed of the slideshow cycling, in milliseconds
	                animationSpeed: 600,            //Integer: Set the speed of animations, in milliseconds
	                initDelay: 0,                   //{NEW} Integer: Set an initialization delay, in milliseconds
	                randomize: false,               //Boolean: Randomize slide order
	                directionNav: false,
                    prevText: "",                   //String: Set the text for the "previous" directionNav item
	                nextText: ""                    //String: Set the text for the "next" directionNav item
	            });
	            var winx = ($(window).width() - 960) / 2;
	            var winy = $(window).width() / 4
	            $(".flex-banner").css({
	                left: winx + "px",
	                top: winy - 200 + "px",
	                padding: 25 + "px"
	            });
	            $(".flex-banner-text").css({
	                width: 900 + "px",
	                height: 80 + "px",
	                padding: 0,
	                margin: 30 + "px auto"
	            });
	            $(".logo").css({
	                display: "block"
	            });
	            $(".flexslider").css({
	                display: "block"
	            });
	            $(".flex-banner").css({
	                display: "block"
	            });
	            $("#body").css({
	                top: 200 + "px"
	            });
	        }

	        function fnMobileHeader() {
	            $(".logo").css({
	                display: "none"
	            });
	            $(".flexslider").css({
	                display: "none"
	            });
	            $(".flex-banner").css({
	                display: "none"
	            });
	            $("#body").css({
	                top: 50 + "px"
	            });
	        }
	    });
	</script>
</head>
<body>
	<div id="header">
    <nav class="nav-collapse">
	    <ul class="main">
		    <li id="home" class="first"><a href="home.htm">home</a></li>        
		    <li id="services"><a href="services.htm">services</a>
			    <ul>
				    <li><a href="servicedetail.htm?warehouse" id="warehouse">Warehousing & Fulfilment</a></li>
				    <li><a href="servicedetail.htm?mail" id="mail">Mail & Distribution</a></li>
				    <li><a href="servicedetail.htm?production" id="production">Production services</a></li>
				    <li><a href="servicedetail.htm?support" id="support">Support Services</a></li>
			    </ul>
		    </li>
		    <li id="profile"><a href="aboutus.htm">About Us</a>
		    </li>
		    <li id="contact"><a href="contactus.htm">contact us</a></li>
		    <li id="login"><a href="https://clients.nationalmailing.com.au/Public/Account/Login">Client Login</a></li>
	    </ul>
    </nav>
    <div class="logo">
	    <a href="home.htm"><img src="images/logo.png" alt=""></a>
    </div>
    </div>
    <div id="body">
    <div class="flex-banner">
        <p class="flex-banner-text">Your independent warehouse, mailhouse and distribution specialist</p>
        <a href="aboutus.htm" class="flex-banner-link">Learn more</a>
    </div>
    <!--rollover images, window width-->
    <div class="flexslider">
        <ul class="slides">
            <li>
                <img src="images/kitchen_adventurer_caramel.jpg" />
            </li>
            
            <li>
                <img src="images/kitchen_adventurer_cheesecake_brownie.jpg" />
            </li>
            <li>
                <img src="images/kitchen_adventurer_donut.jpg" />
            </li>
        </ul>
        
    </div>
    <div class="section">
    <h1>Services</h1>
    <div class="sub-section" style="width:220px;">
    <h2>Warehousing</h2>
    Warehousing and inventory control <br />
    Mail house services<br />
    support services
    </div>
    <div class="sub-section" style="width:220px;">
    <h2>Mail & distribution</h2>
    Government<br />
    Private
    </div>
    <div class="sub-section" style="width:220px;">
    <h2>Production servieces</h2>
    Government<br />
    Private
    </div>
    <div class="sub-section" style="width:220px;">
    <h2>Support services</h2>
    Government<br />
    Private
    </div>    
    <div class="sub-section" style="width:98%; text-align:right; border-bottom:4px solid #007229;">
        <a class="readmore" href="#">Read more</a>
    </div>
    </div>
    <div class="section">
    <h1>About us</h1>
    <div class="sub-section">National Mailing & Marketing (NMM) kdskds jdsldaskjfakdfjla  ksdhfa  adjkfhasd fAAAAAAA A AA AAAAAAAAAAAAAAA A AA AAAAAAAAA AAAAA A</div>
    <div class="sub-section" style="width:310px; text-align:center;">
        <image src="images/person.png" /><br />
        <h2>lyndall TheilMann</h2>
        Derector
    </div>
    <div class="sub-section" style="width:310px; text-align:center;">        
        <image src="images/person.png" /><br />
        <h2>Steve Conroy</h2>
        Derector
    </div>
    <div class="sub-section" style="width:310px; text-align:center;">
        <image src="images/person.png" /><br />
        <h2>Dennis Ogden</h2>
        General Manager
    </div>
    <div class="sub-section" style="width:98%; text-align:right;border-bottom:4px solid #007229;">
        <a class="readmore" href="#">Read more</a>
    </div>
    </div>
    <div class="section">
    <h1>Contact us</h1>
    <div class="sub-section" style="max-width:460px;">
        at <strong>NMM</strong> skdfhaklsd asdfkaksdf asdfkja df as<br />
     
        <div id="contactusform">
        </div>
    </div>
    <div class="sub-section" style="max-width:460px;">
        <table>
            <tr>
                <td><img src="images/icon-phone.png" alt="icon-phone" /></td>
                <td>1300 131 616</td>
            </tr>
            <tr>
                <td><img src="images/icon-fax.png" alt="icon-fax" /></td>
                <td>02 6260 2770</td>
            </tr>
            <tr>
                <td><img src="images/icon-email.png" alt="icon-email" /></td>
                <td>contactus@nationalmailing.com.au</td>
            </tr>
            <tr>
                <td><img src="images/icon-home.png" alt="icon-home" /></td>
                <td>11 Tralee Steet Hume ACT 2620</td>
            </tr>
            <tr><td colspan="2">
            <iframe width="450" height="350" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=National+Mailing+%26+Marketing,+Tralee+Street,+Hume,+Australian+Capital+Territory,+Australia&amp;aq=0&amp;oq=National+Mail11+Tralee+Street,+Hume,+Australian+Capital+Territory,+Australia&amp;sll=-35.39539,149.16101&amp;sspn=0.007775,0.009645&amp;g=11+Tralee+Street,+Hume,+Australian+Capital+Territory,+Australia&amp;ie=UTF8&amp;hq=National+Mailing+%26+Marketing,&amp;hnear=Tralee+St,+Hume+Australian+Capital+Territory+2620,+Australia&amp;t=m&amp;cid=4172785864488464185&amp;ll=-35.377574,149.168758&amp;spn=0.062984,0.085659&amp;z=13&amp;iwloc=A&amp;output=embed" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe><br>
            <a style="text-align: left;" href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=National+Mailing+%26+Marketing,+Tralee+Street,+Hume,+Australian+Capital+Territory,+Australia&amp;aq=0&amp;oq=National+Mail11+Tralee+Street,+Hume,+Australian+Capital+Territory,+Australia&amp;sll=-35.39539,149.16101&amp;sspn=0.007775,0.009645&amp;g=11+Tralee+Street,+Hume,+Australian+Capital+Territory,+Australia&amp;ie=UTF8&amp;hq=National+Mailing+%26+Marketing,&amp;hnear=Tralee+St,+Hume+Australian+Capital+Territory+2620,+Australia&amp;t=m&amp;cid=4172785864488464185&amp;ll=-35.377574,149.168758&amp;spn=0.062984,0.085659&amp;z=13&amp;iwloc=A" target="_blanck">View Larger Map</a></td></tr>
        </table>
    </div>
    </div>    
    <div id="footer"></div>
    </div>
<script>
    var navigation = responsiveNav(".nav-collapse");
</script>
</body>
</html>
